### ISSUE TITLE
Weird loop behavior with -O2 optimization

### ISSUE THREAD

**Issue by stkeke** [dstogov/ir#40]
I am still quite native to IR construction APIs and programming, so my IR function to implement a for loop could be fundamentally wrong! Please advise.
# my IR function
```C
void gen_myfunc(ir_ctx *ctx)
{
	ir_START();
	ir_ref cnt = ir_PARAM(IR_I32, "loop_count", 1);

	ir_ref init_idx = ir_CONST_I32(1);
	ir_ref init_total = ir_CONST_I32(0);

	/* loop begin */
	ir_ref loop = ir_LOOP_BEGIN(ir_END());

	ir_ref phi_idx = ir_PHI_2(init_idx, IR_UNUSED);
	ir_ref phi_total = ir_PHI_2(init_total, IR_UNUSED);

	ir_ref if1 = ir_IF(ir_LE(phi_idx, cnt));
	ir_IF_TRUE(if1);
		ir_ref phi_idx_2 = ir_ADD_I32(phi_idx, ir_CONST_I32(1));
		ir_ref ret = ir_ADD_I32(phi_total, phi_idx);
		ir_ref loop_end = ir_LOOP_END(); /* loop end */
	ir_IF_FALSE(if1); /* loop exit */
		ir_RETURN(ret);
	ir_MERGE_SET_OP(loop, 2, loop_end);
	ir_PHI_SET_OP(phi_idx, 2, phi_idx_2);
	ir_PHI_SET_OP(phi_total, 2, ret);
}
```
After `ir_jit_compile()` with O2, `ir_ref ret = ir_ADD_I32(phi_total, phi_idx);` unexpectedly (at least to me) moved between `LE` and `IF` (expect to be placed after `IF_TRUE`: do addition only when `idx<=loop_count`); hence, do one more addition than expected. 

![image](https://github.com/dstogov/ir/assets/6504403/4d49825c-9613-48b5-8cf9-d0a9880aa5a4)

**Comment by stkeke** [comment]
@dstogov Thanks for the hint. It's time to grab some paper and read ...

**Comment by dstogov** [comment]
See the list at the end of the README.md

**Comment by stkeke** [comment]
Thanks. 
IR construction APIs look like assembly instructions but actually they are not...Those papers are worth reading.
